Copyright (c) European Space Agency, 2026.  
This file is subject to the terms and conditions defined in file 'LICENCE.txt',   
which is part of this source code package. No part of the package, including  
this file, may be copied, modified, propagated, or distributed except according to   
the terms contained in the file ‘LICENCE.txt’.

# Download the pre-release epoch_astrometry dataset from the public FTP server and analyse it using `gaiasupdate`

The `gaiasupdate` package can be found at https://github.com/esa/gaia-supdate.  
It can be installed with `pip install gaiasupdate`

In [15]:
import logging
import urllib.request
import zipfile
import os
import glob

import numpy as np
import pandas as pd

from gaiasupdate.epoch_astrometry import GaiaEpochAstrometryArchive
from astropy.table import Table

logger = logging.getLogger()
logger.setLevel(logging.INFO)

## Download astrometric-timeseries data

In [16]:
# URL of the file to download
url = "https://anonftp.cosmos.esa.int/pub/GAIA_PUBLIC_DATA/Gaia_DR4/dr4-prerelease/gaia-dr4-prerelease-epoch-astrometry_2026-06-26.zip"

local_dir = os.getcwd()

# Define download path
download_path = os.path.join(local_dir, 'downloaded_file.zip')
extract_path = os.path.join(local_dir, 'extracted_files')

if not os.path.isfile(download_path):

    # Download the file
    urllib.request.urlretrieve(url, os.path.basename(download_path))
    logging.info(f"Downloaded {url} to {os.path.basename(download_path)}")

with zipfile.ZipFile(download_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)
logging.info(f"Extracted {os.path.basename(download_path)} to {os.path.basename(extract_path)}")

INFO:root:Extracted downloaded_file.zip to extracted_files

In [17]:
epoch_astrometry_file = glob.glob(os.path.join(extract_path, '*.xml'))[0]
logging.info(f"Found epoch astrometry file: {os.path.basename(epoch_astrometry_file)}")

INFO:root:Found epoch astrometry file: GAIA_DR4_PRERELEASE_EPOCH_ASTROMETRY_RAW.xml

In [18]:
# Read VOTable with astropy.table and convert to pandas
table = Table.read(epoch_astrometry_file, format="votable")
df = table.to_pandas()
logging.info(f"File contains data for {df['source_id'].nunique()} unique sources.\n")
display(df.info())

INFO:root:File contains data for 12 unique sources.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   solution_id                1008 non-null   int64
 1   source_id                  1008 non-null   int64
 2   transit_id                 1008 non-null   int64
 3   ra0                        1008 non-null   float64
 4   dec0                       1008 non-null   float64
 5   agis_source_excess_noise   1008 non-null   float32
 6   obs_time_tcb               1008 non-null   object
 7   obs_time_bary_corr         911 non-null    float32
 8   scan_pos_angle             1008 non-null   object
 9   zeta                       911 non-null    float32
 10  parallax_factor_al         911 non-null    float32
 11  parallax_factor_ac         911 non-null    float32
 12  colour_factor_al           1008 non-null   object
 13  colour_factor_ac           1008 non-null   object
 14  nu_eff_used_in_astrometry  1008 non-null   float32
 15  nu_eff_error               1008 non-null   float32
 16  centroid_pos_al            1008 non-null   object
 17  centroid_pos_ac            0 non-null      object
 18  calculated_pos_ac          1008 non-null   object
 19  centroid_pos_error_al      1008 non-null   object
 20  centroid_pos_error_ac      0 non-null      object
 21  used_by_agis_al            1008 non-null   object
 22  used_by_agis_ac            1008 non-null   object
 23  transit_acq_flags          1008 non-null   int16
 24  transit_proc_flags         1008 non-null   int16
 25  ccd_proc_flags             1008 non-null   object
 26  multipeak                  1008 non-null   bool
 27  blended                    1008 non-null   bool
 28  ipd_error_al               1008 non-null   object
 29  ipd_error_ac               1008 non-null   object
 30  g_mag                      1008 non-null   float32
 31  g_class                    1008 non-null   int16
 32  gates                      1008 non-null   object
 33  source_dist_to_last_ci     1008 non-null   object
 34  ac_rate                    1008 non-null   float32
 35  sub_pixel_coord            1008 non-null   object
 36  mu                         1008 non-null   object
dtypes: bool(2), float32(9), float64(2), int16(3), int64(3), object(18)
memory usage: 224.6+ KB

None

In [19]:
# helper function 
def map_results(sourceid, supdate):

    supdate_results = {}
    params = ['deltaAlphaStar_mas', 'deltaDelta_mas', 'varpi_mas', 'muAlphaStar_maspyr', 'muDelta_maspyr', 'pseudoColor_offset']
    
    supdate_results['sourceId'] = sourceid
    supdate_results['success'] = np.where(np.isnan(supdate['parameters'][2]), 0, 1).item()
    supdate_results['paramsSolved'] = np.where(supdate['model'] == '6p_constrained_colour', 95, 31).item()
    
    agis_ppm_keys = [ f'{s}' for s in params ]
    agis_ppm_error_keys = [ f'{p}Error' for p in params ]
                
    map_source_to_results = {'excessNoise': 'excess_noise', 'excessNoiseSig': 'significance' }
    map_source_to_statistic = { 'f2': 'f2', 'chi2Al': 'chi2', 'nObsAl': 'n_measurements', 'nOutliersAl': 'n_outliers' }

    for field, mapped_field in map_source_to_results.items(): supdate_results[field] = supdate[mapped_field]
        
    for field, mapped_field in map_source_to_statistic.items(): supdate_results[field] = getattr(supdate['solution_statistic'], mapped_field)
        
    for i, key in enumerate(agis_ppm_error_keys): supdate_results[key] = supdate['parameters_formal_uncertainty'][i]

    for i, key in enumerate(agis_ppm_keys): supdate_results[key] = supdate['parameters'][i]

    return supdate_results

## Perform the single-star model fit in the same way as the core astrometric solution of Gaia DR4, but on epoch_astrometry data

The output parameters of the `GaiaEpochAstrometryArchive.supdate` method are described at https://esa.github.io/gaia-supdate/supdate_output_params.html

In [20]:
epoch_astro = df.copy()

for source_id in df['source_id'].unique():
    logging.info(f"Processing source_id: {source_id}")
    res_6p = GaiaEpochAstrometryArchive.supdate(epoch_astro, source_id)

    res_6p_df = pd.DataFrame( [map_results(source_id, res_6p)] )
    display(res_6p_df[['deltaAlphaStar_mas', 'deltaDelta_mas', 'varpi_mas', 'muAlphaStar_maspyr', 'muDelta_maspyr', 'pseudoColor_offset', 'paramsSolved']])

INFO:root:Processing source_id: 4181040337841125632
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on usedByAgisAl==True removed 333 entries.
INFO:root:Filter on column obsTimeBaryCorr!=null removed 0 entries.
INFO:root:Filter on column scanPosAngle!=null removed 0 entries.
INFO:root:GaiaSourceEpochAstrometryCu9 for source_id 4181040337841125632 with 637 CCD         transits

,deltaAlphaStar_mas,deltaDelta_mas,varpi_mas,muAlphaStar_maspyr,muDelta_maspyr,pseudoColor_offset,paramsSolved
0,-0.000002,4.894602e-08,1.001305,2.903832,-0.294277,0.000002,95

INFO:root:Processing source_id: 435469040545191680
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on usedByAgisAl==True removed 161 entries.
INFO:root:Filter on column obsTimeBaryCorr!=null removed 0 entries.
INFO:root:Filter on column scanPosAngle!=null removed 0 entries.
INFO:root:GaiaSourceEpochAstrometryCu9 for source_id 435469040545191680 with 649 CCD         transits

,deltaAlphaStar_mas,deltaDelta_mas,varpi_mas,muAlphaStar_maspyr,muDelta_maspyr,pseudoColor_offset,paramsSolved
0,-0.000013,-0.000008,0.997734,3.421709,-5.812479,-3.402614e-07,95

INFO:root:Processing source_id: 3926186255616949504
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on usedByAgisAl==True removed 348 entries.
INFO:root:Filter on column obsTimeBaryCorr!=null removed 0 entries.
INFO:root:Filter on column scanPosAngle!=null removed 0 entries.
INFO:root:GaiaSourceEpochAstrometryCu9 for source_id 3926186255616949504 with 462 CCD         transits

,deltaAlphaStar_mas,deltaDelta_mas,varpi_mas,muAlphaStar_maspyr,muDelta_maspyr,pseudoColor_offset,paramsSolved
0,0.000002,0.000001,0.999329,-9.320931,-0.51077,0.000059,95

INFO:root:Processing source_id: 2309425390592896
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on usedByAgisAl==True removed 153 entries.
INFO:root:Filter on column obsTimeBaryCorr!=null removed 0 entries.
INFO:root:Filter on column scanPosAngle!=null removed 0 entries.
INFO:root:GaiaSourceEpochAstrometryCu9 for source_id 2309425390592896 with 597 CCD         transits

,deltaAlphaStar_mas,deltaDelta_mas,varpi_mas,muAlphaStar_maspyr,muDelta_maspyr,pseudoColor_offset,paramsSolved
0,0.000006,0.000002,0.926211,7.200292,-3.322024,0.000004,95

INFO:root:Processing source_id: 20694084440761600
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on usedByAgisAl==True removed 164 entries.
INFO:root:Filter on column obsTimeBaryCorr!=null removed 0 entries.
INFO:root:Filter on column scanPosAngle!=null removed 0 entries.
INFO:root:GaiaSourceEpochAstrometryCu9 for source_id 20694084440761600 with 576 CCD         transits

,deltaAlphaStar_mas,deltaDelta_mas,varpi_mas,muAlphaStar_maspyr,muDelta_maspyr,pseudoColor_offset,paramsSolved
0,0.000009,0.000004,4.942145,25.441411,-16.504147,-0.000005,95

INFO:root:Processing source_id: 1663617687609809280
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on usedByAgisAl==True removed 169 entries.
INFO:root:Filter on column obsTimeBaryCorr!=null removed 0 entries.
INFO:root:Filter on column scanPosAngle!=null removed 0 entries.
INFO:root:GaiaSourceEpochAstrometryCu9 for source_id 1663617687609809280 with 781 CCD         transits

,deltaAlphaStar_mas,deltaDelta_mas,varpi_mas,muAlphaStar_maspyr,muDelta_maspyr,pseudoColor_offset,paramsSolved
0,-0.000189,-0.000215,10.106683,-124.573287,-135.823929,0.000004,95

INFO:root:Processing source_id: 2237987199365376
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on usedByAgisAl==True removed 178 entries.
INFO:root:Filter on column obsTimeBaryCorr!=null removed 0 entries.
INFO:root:Filter on column scanPosAngle!=null removed 0 entries.
INFO:root:GaiaSourceEpochAstrometryCu9 for source_id 2237987199365376 with 702 CCD         transits

,deltaAlphaStar_mas,deltaDelta_mas,varpi_mas,muAlphaStar_maspyr,muDelta_maspyr,pseudoColor_offset,paramsSolved
0,-0.000005,0.00001,-0.002339,0.039354,0.171816,0.00008,95

INFO:root:Processing source_id: 60730287810150016
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on usedByAgisAl==True removed 122 entries.
INFO:root:Filter on column obsTimeBaryCorr!=null removed 0 entries.
INFO:root:Filter on column scanPosAngle!=null removed 0 entries.
INFO:root:GaiaSourceEpochAstrometryCu9 for source_id 60730287810150016 with 608 CCD         transits

,deltaAlphaStar_mas,deltaDelta_mas,varpi_mas,muAlphaStar_maspyr,muDelta_maspyr,pseudoColor_offset,paramsSolved
0,-0.000006,0.000009,0.00321,0.222685,-0.062456,0.00002,95

INFO:root:Processing source_id: 10973744521070720
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on usedByAgisAl==True removed 105 entries.
INFO:root:Filter on column obsTimeBaryCorr!=null removed 0 entries.
INFO:root:Filter on column scanPosAngle!=null removed 0 entries.
INFO:root:GaiaSourceEpochAstrometryCu9 for source_id 10973744521070720 with 515 CCD         transits

,deltaAlphaStar_mas,deltaDelta_mas,varpi_mas,muAlphaStar_maspyr,muDelta_maspyr,pseudoColor_offset,paramsSolved
0,-9.755668e-07,0.000003,0.00265,-0.345856,0.078786,0.00004,95

INFO:root:Processing source_id: 4318465066420528000
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on usedByAgisAl==True removed 212 entries.
INFO:root:Filter on column obsTimeBaryCorr!=null removed 0 entries.
INFO:root:Filter on column scanPosAngle!=null removed 0 entries.
INFO:root:GaiaSourceEpochAstrometryCu9 for source_id 4318465066420528000 with 558 CCD         transits

,deltaAlphaStar_mas,deltaDelta_mas,varpi_mas,muAlphaStar_maspyr,muDelta_maspyr,pseudoColor_offset,paramsSolved
0,-0.000022,-0.000339,1.960751,-30.739616,-148.926288,0.00003,95

INFO:root:Processing source_id: 3937211745905473024
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on usedByAgisAl==True removed 342 entries.
INFO:root:Filter on column obsTimeBaryCorr!=null removed 0 entries.
INFO:root:Filter on column scanPosAngle!=null removed 0 entries.
INFO:root:GaiaSourceEpochAstrometryCu9 for source_id 3937211745905473024 with 558 CCD         transits

,deltaAlphaStar_mas,deltaDelta_mas,varpi_mas,muAlphaStar_maspyr,muDelta_maspyr,pseudoColor_offset,paramsSolved
0,0.001366,-0.000123,25.631659,-582.029241,-0.708667,0.000014,95

INFO:root:Processing source_id: 1457486023639239296
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on column obsTimeTcb!=null removed 0 entries.
INFO:root:Filter on usedByAgisAl==True removed 326 entries.
INFO:root:Filter on column obsTimeBaryCorr!=null removed 0 entries.
INFO:root:Filter on column scanPosAngle!=null removed 0 entries.
INFO:root:GaiaSourceEpochAstrometryCu9 for source_id 1457486023639239296 with 824 CCD         transits

,deltaAlphaStar_mas,deltaDelta_mas,varpi_mas,muAlphaStar_maspyr,muDelta_maspyr,pseudoColor_offset,paramsSolved
0,-0.000037,0.000009,13.624072,-75.552329,17.943998,-5.029289e-07,95